<a href="https://colab.research.google.com/github/AI-fanatic24/machine-learning-foundations/blob/main/Mushroom_Classification_Edible_or_Poisonous.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
df = pd.read_csv('/content/mushrooms.csv')
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l


In [ ]:
one_hot_features = ['cap-shape','cap-surface','cap-color','bruises','odor','gill-attachment','gill-spacing','gill-size','gill-color','stalk-shape','stalk-root','stalk-surface-above-ring','stalk-surface-below-ring','stalk-color-above-ring','stalk-color-below-ring','veil-type','veil-color','ring-number','ring-type','spore-print-color','population','habitat']

In [ ]:
df = pd.get_dummies(data=df,prefix=one_hot_features,columns=one_hot_features)

In [ ]:
df

,class,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,p,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,1,0
1,e,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,e,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,p,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
4,e,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8120,e,0,0,0,0,0,1,0,0,1,...,0,1,0,0,0,1,0,0,0,0
8121,e,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8122,p,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0


In [ ]:
df.loc[df["class"] == "p","class"] = 0      # 0 = poisonous
df.loc[df["class"] == "e","class"] = 1      # 1 = edible

In [ ]:
df

,class,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,0,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,1,0
1,1,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
4,1,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,1,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8120,1,0,0,0,0,0,1,0,0,1,...,0,1,0,0,0,1,0,0,0,0
8121,1,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8122,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0


In [ ]:
features = [x for x in df.columns if x not in ['class']]

In [ ]:
X_train,X_,y_train,y_ = train_test_split(df[features],df['class'],train_size=0.60,random_state=1)
X_val,X_test,y_val,y_test = train_test_split(X_,y_,train_size=0.50,random_state=1)
del X_,y_

In [ ]:
X_train = np.array(X_train,dtype='float32')
X_val = np.array(X_val,dtype='float32')
y_train = np.array(y_train,dtype='float32').reshape(-1,1)
y_val = np.array(y_val,dtype='float32').reshape(-1,1)
X_test = np.array(X_test,dtype='float32')
y_test = np.array(y_test,dtype='float32').reshape(-1,1)

In [ ]:
print("X_train.shape",X_train.shape)
print("y_train.shape",y_train.shape)
print("X_val.shape",X_val.shape)
print("y_val.shape",y_val.shape)
print("X_test.shape",X_test.shape)
print("y_test.shape",y_test.shape)

X_train.shape (4874, 117)
y_train.shape (4874, 1)
X_val.shape (1625, 117)
y_val.shape (1625, 1)
X_test.shape (1625, 117)
y_test.shape (1625, 1)


In [ ]:
xgb_model = XGBClassifier(n_estimators=200,learning_rate=0.2,verbosity=1,random_state=1)
xgb_model.fit(X_train,y_train,eval_set=[(X_val,y_val)],early_stopping_rounds=5)

[0]	validation_0-logloss:0.51438
[1]	validation_0-logloss:0.39461
[2]	validation_0-logloss:0.30869
[3]	validation_0-logloss:0.24472
[4]	validation_0-logloss:0.19593
[5]	validation_0-logloss:0.15811
[6]	validation_0-logloss:0.12844
[7]	validation_0-logloss:0.10491
[8]	validation_0-logloss:0.08567
[9]	validation_0-logloss:0.07024
[10]	validation_0-logloss:0.05784
[11]	validation_0-logloss:0.04778
[12]	validation_0-logloss:0.03932
[13]	validation_0-logloss:0.03247
[14]	validation_0-logloss:0.02685
[15]	validation_0-logloss:0.02228
[16]	validation_0-logloss:0.01864
[17]	validation_0-logloss:0.01557
[18]	validation_0-logloss:0.01312
[19]	validation_0-logloss:0.01121
[20]	validation_0-logloss:0.00968
[21]	validation_0-logloss:0.00834
[22]	validation_0-logloss:0.00722
[23]	validation_0-logloss:0.00627
[24]	validation_0-logloss:0.00548
[25]	validation_0-logloss:0.00483
[26]	validation_0-logloss:0.00434
[27]	validation_0-logloss:0.00386
[28]	validation_0-logloss:0.00354
[29]	validation_0-loglos

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.2, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, random_state=1, ...)

In [ ]:
xgb_model.best_iteration

199

In [ ]:
print("Train accuracy: ",accuracy_score(xgb_model.predict(X_train),y_train))
print("Validation accuracy: ",accuracy_score(xgb_model.predict(X_val),y_val))
print("Test accuracy: ",accuracy_score(xgb_model.predict(X_test),y_test))

Train accuracy:  1.0
Validation accuracy:  1.0
Test accuracy:  1.0


In [ ]:
train_pred = xgb_model.predict(X_train)
val_pred = xgb_model.predict(X_val)
test_pred = xgb_model.predict(X_test)

In [ ]:
print("Train Confusion Matrix:\n",confusion_matrix(y_train,train_pred))
print("Validation Confusion Matrix:\n",confusion_matrix(y_val,val_pred))
print("Test Confusion Matrix:\n",confusion_matrix(y_test,test_pred))

Train Confusion Matrix:
 [[2336    0]
 [   0 2538]]
Validation Confusion Matrix:
 [[782   0]
 [  0 843]]
Test Confusion Matrix:
 [[798   0]
 [  0 827]]


In [ ]:
for i in range(200):
  print("Prediction: ",test_pred[i],"  Actual Value: ",int(y_test[i]))

Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  0   Actual Value:  0
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1   Actual Value:  1
Prediction:  1