<a href="https://colab.research.google.com/github/AI-fanatic24/machine-learning-foundations/blob/main/ReaL_Estate_Predictor_using_sklearn_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import SGDRegressor, LinearRegression
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
df = pd.read_csv("/content/Real Estate.csv")
df

,No,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...
409,410,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,8.1,104.81010,5,24.96674,121.54067,52.5


In [ ]:
X_train = np.array(df[['X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores','X5 latitude','X6 longitude']])
X_train

array([[ 32.     ,  84.87882,  10.     ,  24.98298, 121.54024],
       [ 19.5    , 306.5947 ,   9.     ,  24.98034, 121.53951],
       [ 13.3    , 561.9845 ,   5.     ,  24.98746, 121.54391],
       ...,
       [ 18.8    , 390.9696 ,   7.     ,  24.97923, 121.53986],
       [  8.1    , 104.8101 ,   5.     ,  24.96674, 121.54067],
       [  6.5    ,  90.45606,   9.     ,  24.97433, 121.5431 ]])

In [ ]:
y_train = np.array(df[['Y house price of unit area']])
y_train

array([[ 37.9],
       [ 42.2],
       [ 47.3],
       [ 54.8],
       [ 43.1],
       [ 32.1],
       [ 40.3],
       [ 46.7],
       [ 18.8],
       [ 22.1],
       [ 41.4],
       [ 58.1],
       [ 39.3],
       [ 23.8],
       [ 34.3],
       [ 50.5],
       [ 70.1],
       [ 37.4],
       [ 42.3],
       [ 47.7],
       [ 29.3],
       [ 51.6],
       [ 24.6],
       [ 47.9],
       [ 38.8],
       [ 27. ],
       [ 56.2],
       [ 33.6],
       [ 47. ],
       [ 57.1],
       [ 22.1],
       [ 25. ],
       [ 34.2],
       [ 49.3],
       [ 55.1],
       [ 27.3],
       [ 22.9],
       [ 25.3],
       [ 47.7],
       [ 46.2],
       [ 15.9],
       [ 18.2],
       [ 34.7],
       [ 34.1],
       [ 53.9],
       [ 38.3],
       [ 42. ],
       [ 61.5],
       [ 13.4],
       [ 13.2],
       [ 44.2],
       [ 20.7],
       [ 27. ],
       [ 38.9],
       [ 51.7],
       [ 13.7],
       [ 41.9],
       [ 53.5],
       [ 22.6],
       [ 42.4],
       [ 21.3],
       [ 63.2],
       [

In [ ]:
scaler = StandardScaler()
X_norm = scaler.fit_transform(X_train)
X_norm

array([[ 1.25562833, -0.79249504,  2.00740743,  1.12542986,  0.44876222],
       [ 0.15708622, -0.61661163,  1.66750286,  0.91244418,  0.40113894],
       [-0.38779067, -0.41401527,  0.30788458,  1.48686011,  0.68818339],
       ...,
       [ 0.09556786, -0.54967846,  0.98769372,  0.82289338,  0.42397202],
       [-0.84478419, -0.77668389,  0.30788458, -0.18475479,  0.4768143 ],
       [-0.98539758, -0.78807071,  1.66750286,  0.42757905,  0.63534112]])

In [ ]:
sgdr = SGDRegressor(max_iter=1000)
sgdr.fit(X_norm,y_train)
print(sgdr)

SGDRegressor()


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
b_norm = sgdr.intercept_
w_norm = sgdr.coef_
print(f"model parameters are: w={w_norm} b={b_norm}")

model parameters are: w=[-3.0098289  -5.14139691  3.47438014  2.98576924  0.02756036] b=[38.00391327]


In [ ]:
m,_ = X_norm.shape
y_pred_sgd = sgdr.predict(X_norm)
for i in range(m):
  print(f"Prediction:{y_pred_sgd[i]:.1f}---Target Value:{y_train[i]}")

Prediction:48.6---Target Value:[37.9]
Prediction:49.2---Target Value:[42.2]
Prediction:46.8---Target Value:[47.3]
Prediction:46.8---Target Value:[54.8]
Prediction:47.8---Target Value:[43.1]
Prediction:33.6---Target Value:[32.1]
Prediction:41.4---Target Value:[40.3]
Prediction:45.6---Target Value:[46.7]
Prediction:8.1---Target Value:[18.8]
Prediction:33.4---Target Value:[22.1]
Prediction:33.7---Target Value:[41.4]
Prediction:52.2---Target Value:[58.1]
Prediction:41.8---Target Value:[39.3]
Prediction:29.6---Target Value:[23.8]
Prediction:44.2---Target Value:[34.3]
Prediction:36.1---Target Value:[50.5]
Prediction:50.2---Target Value:[70.1]
Prediction:38.9---Target Value:[37.4]
Prediction:45.4---Target Value:[42.3]
Prediction:49.7---Target Value:[47.7]
Prediction:33.9---Target Value:[29.3]
Prediction:48.2---Target Value:[51.6]
Prediction:30.0---Target Value:[24.6]
Prediction:48.3---Target Value:[47.9]
Prediction:35.7---Target Value:[38.8]
Prediction:32.3---Target Value:[27.]
Prediction:48.

In [ ]:
score = r2_score(y_train,y_pred_sgd)
print("This model has",round(score,2)*100,"% accuracy")

This model has 56.99999999999999 % accuracy


BETTER APPROACH

In [ ]:
X_train,X_,y_train,y_ = train_test_split(X_train,y_train,test_size=0.40,random_state=1)
X_cv,X_test,y_cv,y_test = train_test_split(X_,y_,test_size=0.50,random_state=1)
del X_,y_

In [ ]:
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("X_cv shape: ",X_cv.shape)
print("y_cv shape: ",y_cv.shape)
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)

X_train shape:  (248, 5)
y_train shape:  (248, 1)
X_cv shape:  (83, 5)
y_cv shape:  (83, 1)
X_test shape:  (83, 5)
y_test shape:  (83, 1)


In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [ ]:
model = LinearRegression()
model.fit(X_train_scaled,y_train)

LinearRegression()

In [ ]:
yhat = model.predict(X_train_scaled)
print("Traning MSE: ", mean_squared_error(y_train,yhat)/2)

Traning MSE:  31.163537112791655


In [ ]:
X_cv_scaled = scaler.transform(X_cv)
model.fit(X_cv_scaled,y_cv)

LinearRegression()

In [ ]:
yhat = model.predict(X_cv_scaled)
print("Validation MSE: ",mean_squared_error(y_cv,yhat)/2)

Validation MSE:  55.46225989403807


In [ ]:
poly = PolynomialFeatures(degree=2,include_bias=False)
X_train_mapped = poly.fit_transform(X_train)

In [ ]:
scaler_poly = StandardScaler()
X_train_mapped_scaled = scaler_poly.fit_transform(X_train_mapped)

In [ ]:
linear_model = LinearRegression()
linear_model.fit(X_train_mapped_scaled,y_train)

LinearRegression()

In [ ]:
yhat = linear_model.predict(X_train_mapped_scaled)
print("Traning MSE: ", mean_squared_error(y_train,yhat)/2)

Traning MSE:  21.16174272776246


In [ ]:
X_cv_mapped = poly.fit_transform(X_cv)
X_cv_mapped_scaled = scaler_poly.transform(X_cv_mapped)

linear_model.fit(X_cv_mapped_scaled,y_cv)

yhat = linear_model.predict(X_cv_mapped_scaled)
print("Validation MSE: ",mean_squared_error(y_cv,yhat)/2)

Validation MSE:  36.96859906075074


In [ ]:
X_test_mapped = poly.fit_transform(X_test)
X_test_mapped_scaled = scaler_poly.transform(X_test_mapped)

yhat = linear_model.predict(X_test_mapped_scaled)
print("Testing MSE: ",mean_squared_error(y_test,yhat)/2)

Testing MSE:  63.84580766756381


In [ ]:
train_mses = []
cv_mses = []
scalers = []
models = []
for degree in range (1,11):
  poly = PolynomialFeatures(degree, include_bias = False)
  X_train_mapped = poly.fit_transform(X_train)

  scaler_poly = StandardScaler()
  X_train_mapped_scaled = scaler_poly.fit_transform(X_train_mapped)
  scalers.append(scaler_poly)

  model = LinearRegression()
  model.fit(X_train_mapped_scaled, y_train)
  models.append(model)

  yhat = model.predict(X_train_mapped_scaled)
  train_mse = mean_squared_error(y_train,yhat) / 2
  train_mses.append(train_mse)

  X_cv_mapped = poly.fit_transform(X_cv)
  X_cv_mapped_scaled = scaler_poly.transform(X_cv_mapped)

  yhat = model.predict(X_cv_mapped_scaled)
  cv_mse = mean_squared_error(y_cv,yhat) / 2
  cv_mses.append(cv_mse)

In [ ]:
cv_mses

[68.22665813906681,
 56.699873374867416,
 55.47263416886739,
 1594.3399968015103,
 664453.869316202,
 17527000867320.111,
 5028674482845.785,
 3.905532369831553e+16,
 1.4450884212952934e+16,
 7739223109668189.0]

In [ ]:
degree = np.argmin(cv_mses)
print(degree)

2


In [ ]:
degree = 2
poly = PolynomialFeatures(degree, include_bias = False)
X_test_mapped = poly.fit_transform(X_test)

X_test_mapped_scaled = scalers[degree - 1].transform(X_test_mapped)

yhat = models[degree - 1].predict(X_test_mapped_scaled)
test_mse = mean_squared_error(y_test, yhat) / 2

print(f"Traning MSE: {train_mses[degree - 1]}")
print(f"Cross Validation MSE: {cv_mses[degree - 1]}")
print(f"Test MSE: {test_mse}")
print('\n')
print(f"Testing accuracy is: {round(r2_score(y_test,yhat),2)*100}%")

Traning MSE: 21.16174272776246
Cross Validation MSE: 56.699873374867416
Test MSE: 33.42366094245753


Testing accuracy is: 64.0%
